name: 'Validate Package Exports'
description: Validate the exports of package.json files to ensure they exist, have valid syntax, and can be imported/required
inputs:
  inputFiles: # id of input
    description: 'Path to the package.json file to validate, accepts path to a single file or a glob pattern'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
